name = "difflog"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "difflog-db"
database_id = "e2a8a909-e155-42af-aa75-4bc911278554"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "KV"
id = "a2dae57156264ebebdf583e9c0e4c304"

[vars]
# Environment variables can be set here or via wrangler secret

